FEAT: 프리셋 설정 페이지
oasisbot24/cloud-fe pull request #26
Opened 2024-03-10 14:03 UTC by nrudev

2024-03-13 14:15 UTC, DeveloperRyou approved these changes

2024-03-13 14:15 UTC, DeveloperRyou commented on src/apis/getPresets.ts
preset.ts 에서 get, post 함수 둘다 관리해도 좋을것 같습니다.

2024-03-24 14:33 UTC, DeveloperRyou requested changes

2024-03-24 14:33 UTC, DeveloperRyou commented on src/apis/presets.ts
네트워크 function 리턴타입 붙여주시면 좋겠습니다.

2024-03-24 14:33 UTC, DeveloperRyou commented on src/apis/presets.ts
catch 부분 삭제 필요합니다! useQuery에서 처리가 됩니다

2024-03-24 14:33 UTC, DeveloperRyou commented on src/hooks/preset/usePreset.tsx
@jeongwon0410 커스텀 훅 레퍼런스로 사용해주세요!

2024-03-24 14:33 UTC, DeveloperRyou commented on src/datas/preset.ts
> +};
atom 객체, 타입 정의해서 관리해주세요

2024-03-31 10:16 UTC, nrudev commented on src/datas/preset.ts
> +};
혹시 atom 타입이 object인 경우에 각 키별로 atom을 또 별도로 줄 수 있는게 ["atoms in atom"](https://jotai.org/docs/guides/atoms-in-atom) 이 부분 맞나요?
도큐먼트 보고 이런 식으로 적용해봤는데 여기서 각 키별로 준 atom에 대한 setter를 어떻게 갖다 써야 하는지 잘 모르겟어요.

```
const presetAtom = atom({
  presetName: atom<string>(""),
  indicatorName: atom<string>("TD_Sequential"),
  position: atom<string>("long"),
  profitCutRate: atom<string>("0"),
  lossCutRate: atom<string>("0"),
});
```

2024-03-31 14:22 UTC, DeveloperRyou commented on src/apis/presets.ts
> +}
```
interface CommonResponse<T> {
  msg:string,
  state: "success" | "fail",
  data?: T
}

function getPresets() : Promise<AxiosResponse<CommonResponse<Preset[]>> > {
  return api.get("/preset");
}

const { data: presets } = await getPresets();

2024-03-31 14:22 UTC, DeveloperRyou commented on src/apis/presets.ts
> +    });
then 제거해야 할거 같아요

2024-04-07 14:09 UTC, DeveloperRyou approved these changes
LGTM

2024-04-07 14:09 UTC, DeveloperRyou commented on src/apis/presets.ts
> +}
function getPresets(): Promise<CommonResponse<Preset[]>> {
 const {data} =  api.get("/preset");
 return data;
}

2024-04-07 14:10 UTC, merged