FEAT: CustomSelect 컴포넌트
oasisbot24/cloud-fe pull request #47
Opened 2024-04-27 13:08 UTC by nrudev

2024-04-27 14:12 UTC, DeveloperRyou requested changes

2024-04-27 14:12 UTC, DeveloperRyou commented on src/cards/PresetsCard/index.tsx
CustomSelect를 사용하는 3가지 훅을 생성
훅에서 리턴은 state, component 리턴
이후 index에서 리턴된 값 잡아서 사용

2024-05-01 14:23 UTC, DeveloperRyou requested changes

2024-05-01 14:23 UTC, DeveloperRyou commented on src/hooks/common/useCurrencySelect.tsx
> +  return [currency, CurrencySelect];
return { currency, CurrencySelect };

2024-05-01 14:23 UTC, DeveloperRyou commented on src/cards/PresetsCard/index.tsx
> +  const [market, MarketSelect] = useMarketSelect();
```
  const {priceStatus, PriceStatusSelect}= usePriceStatusSelect();
  const {currency, CurrencySelect} = useCurrencySelect();
  const {market, MarketSelect]}= useMarketSelect();
```
market, MarketSelect 만 각각 필요할 때 코드가 예뻐짐

2024-05-01 14:23 UTC, DeveloperRyou commented on src/hooks/common/useCurrencySelect.tsx
```
type CurrencyType = "won" | "dollar" | "yen";
function useCurrencySelect() {
  const [currency, setCurrency] = useState<CurrencyType>("won");

  function CurrencySelect() {
    return (
      <CustomSelect
        options={[
          { value: "won", label: "원화로" },
          { value: "dollar", label: "달러로" },
          { value: "yen", label: "엔화로" },
        ]}
        state={currency}
        setState={value => setCurrency(value as CurrencyType)}
        indicator={UnfoldMore}
      />
    );
  }

  return { currency, CurrencySelect };
}

```

2024-05-01 14:23 UTC, DeveloperRyou commented on src/datas/basic.ts
잠정적으로 수정필요

2024-05-01 14:24 UTC, nrudev commented on src/hooks/common/useCurrencySelect.tsx
아직 옵션에 들어갈 것이 정해진 것이 없어서 현재는 참고만 하고 추후 반영하겠습니다!

2024-05-01 14:28 UTC, DeveloperRyou approved these changes

2024-05-01 14:28 UTC, merged